// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_adding_img_prop_to_admin_news : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_adding_img_prop_to_admin_news));
        
        string IMigrationMetadata.Id
        {
            get { return "202109221524151_mig_adding_img_prop_to_admin_news"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
