// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_adding_car_type_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_adding_car_type_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202109022047095_mig_adding_car_type_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
