// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_edit_order_add_news_classes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_edit_order_add_news_classes));
        
        string IMigrationMetadata.Id
        {
            get { return "202108021815037_mig_edit_order_add_news_classes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
